In [0]:
import numpy as np

In [27]:
x = np.array([1, 1, 1, 0, 0, 0.5, 0.5, 0])
x

array([1. , 1. , 1. , 0. , 0. , 0.5, 0.5, 0. ])

In [28]:
N = x.shape[0]
bases = 5

A = np.arange(N)[None, :]
A

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [29]:
A = A.repeat(bases, axis=0)
A

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7]])

In [32]:
k = np.arange(5)
k

array([0, 1, 2, 3, 4])

In [30]:
A = A * k[:, None] 
A

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 0,  2,  4,  6,  8, 10, 12, 14],
       [ 0,  3,  6,  9, 12, 15, 18, 21],
       [ 0,  4,  8, 12, 16, 20, 24, 28]])

In [31]:
A = A * 2 * np.pi / N
A

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.78539816,  1.57079633,  2.35619449,  3.14159265,
         3.92699082,  4.71238898,  5.49778714],
       [ 0.        ,  1.57079633,  3.14159265,  4.71238898,  6.28318531,
         7.85398163,  9.42477796, 10.99557429],
       [ 0.        ,  2.35619449,  4.71238898,  7.06858347,  9.42477796,
        11.78097245, 14.13716694, 16.49336143],
       [ 0.        ,  3.14159265,  6.28318531,  9.42477796, 12.56637061,
        15.70796327, 18.84955592, 21.99114858]])

In [41]:
A_c = np.cos(A)
A_c

array([[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17,
        -7.07106781e-01, -1.00000000e+00, -7.07106781e-01,
        -1.83697020e-16,  7.07106781e-01],
       [ 1.00000000e+00,  6.12323400e-17, -1.00000000e+00,
        -1.83697020e-16,  1.00000000e+00,  3.06161700e-16,
        -1.00000000e+00, -4.28626380e-16],
       [ 1.00000000e+00, -7.07106781e-01, -1.83697020e-16,
         7.07106781e-01, -1.00000000e+00,  7.07106781e-01,
         5.51091060e-16, -7.07106781e-01],
       [ 1.00000000e+00, -1.00000000e+00,  1.00000000e+00,
        -1.00000000e+00,  1.00000000e+00, -1.00000000e+00,
         1.00000000e+00, -1.00000000e+00]])

In [42]:
2**(1/2)/2

0.7071067811865476

In [43]:
c_k = A_c @ x
c_k

array([ 4.        ,  1.35355339, -0.5       ,  0.64644661,  1.        ])

In [47]:
A_d = np.sin(A)
A_d

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00,
         7.07106781e-01,  1.22464680e-16, -7.07106781e-01,
        -1.00000000e+00, -7.07106781e-01],
       [ 0.00000000e+00,  1.00000000e+00,  1.22464680e-16,
        -1.00000000e+00, -2.44929360e-16,  1.00000000e+00,
         3.67394040e-16, -1.00000000e+00],
       [ 0.00000000e+00,  7.07106781e-01, -1.00000000e+00,
         7.07106781e-01,  3.67394040e-16, -7.07106781e-01,
         1.00000000e+00, -7.07106781e-01],
       [ 0.00000000e+00,  1.22464680e-16, -2.44929360e-16,
         3.67394040e-16, -4.89858720e-16,  6.12323400e-16,
        -7.34788079e-16,  8.57252759e-16]])

In [48]:
d_k = A_d @ x
d_k

array([ 0.00000000e+00,  8.53553391e-01,  1.50000000e+00, -1.46446609e-01,
       -1.83697020e-16])

In [51]:
np.stack([c_k, d_k], axis=1)

array([[ 4.00000000e+00,  0.00000000e+00],
       [ 1.35355339e+00,  8.53553391e-01],
       [-5.00000000e-01,  1.50000000e+00],
       [ 6.46446609e-01, -1.46446609e-01],
       [ 1.00000000e+00, -1.83697020e-16]])

In [53]:
B = (c_k **2 + d_k **2) ** (1/2)
B

array([4.        , 1.60020629, 1.58113883, 0.66282715, 1.        ])

In [55]:
phi = np.arctan2(d_k, c_k)
phi

array([ 0.00000000e+00,  5.62617536e-01,  1.89254688e+00, -2.22780627e-01,
       -1.83697020e-16])

In [57]:
A_e = np.exp(1j * A)
A_e

array([[ 1.00000000e+00+0.00000000e+00j,  1.00000000e+00+0.00000000e+00j,
         1.00000000e+00+0.00000000e+00j,  1.00000000e+00+0.00000000e+00j,
         1.00000000e+00+0.00000000e+00j,  1.00000000e+00+0.00000000e+00j,
         1.00000000e+00+0.00000000e+00j,  1.00000000e+00+0.00000000e+00j],
       [ 1.00000000e+00+0.00000000e+00j,  7.07106781e-01+7.07106781e-01j,
         6.12323400e-17+1.00000000e+00j, -7.07106781e-01+7.07106781e-01j,
        -1.00000000e+00+1.22464680e-16j, -7.07106781e-01-7.07106781e-01j,
        -1.83697020e-16-1.00000000e+00j,  7.07106781e-01-7.07106781e-01j],
       [ 1.00000000e+00+0.00000000e+00j,  6.12323400e-17+1.00000000e+00j,
        -1.00000000e+00+1.22464680e-16j, -1.83697020e-16-1.00000000e+00j,
         1.00000000e+00-2.44929360e-16j,  3.06161700e-16+1.00000000e+00j,
        -1.00000000e+00+3.67394040e-16j, -4.28626380e-16-1.00000000e+00j],
       [ 1.00000000e+00+0.00000000e+00j, -7.07106781e-01+7.07106781e-01j,
        -1.83697020e-16-1.00000000e

In [58]:
e_k = A_e @ x
e_k

array([ 4.        +0.00000000e+00j,  1.35355339+8.53553391e-01j,
       -0.5       +1.50000000e+00j,  0.64644661-1.46446609e-01j,
        1.        -1.83697020e-16j])

In [63]:
A_e_neg = np.exp(-1j * A)
A_e_neg

array([[ 1.00000000e+00+0.00000000e+00j,  1.00000000e+00+0.00000000e+00j,
         1.00000000e+00+0.00000000e+00j,  1.00000000e+00+0.00000000e+00j,
         1.00000000e+00+0.00000000e+00j,  1.00000000e+00+0.00000000e+00j,
         1.00000000e+00+0.00000000e+00j,  1.00000000e+00+0.00000000e+00j],
       [ 1.00000000e+00+0.00000000e+00j,  7.07106781e-01-7.07106781e-01j,
         6.12323400e-17-1.00000000e+00j, -7.07106781e-01-7.07106781e-01j,
        -1.00000000e+00-1.22464680e-16j, -7.07106781e-01+7.07106781e-01j,
        -1.83697020e-16+1.00000000e+00j,  7.07106781e-01+7.07106781e-01j],
       [ 1.00000000e+00+0.00000000e+00j,  6.12323400e-17-1.00000000e+00j,
        -1.00000000e+00-1.22464680e-16j, -1.83697020e-16+1.00000000e+00j,
         1.00000000e+00+2.44929360e-16j,  3.06161700e-16-1.00000000e+00j,
        -1.00000000e+00-3.67394040e-16j, -4.28626380e-16+1.00000000e+00j],
       [ 1.00000000e+00+0.00000000e+00j, -7.07106781e-01-7.07106781e-01j,
        -1.83697020e-16+1.00000000e

In [65]:
e_neg_k = A_e_neg @ x
e_neg_k

array([ 4.        +0.00000000e+00j,  1.35355339-8.53553391e-01j,
       -0.5       -1.50000000e+00j,  0.64644661+1.46446609e-01j,
        1.        +1.83697020e-16j])

In [66]:
e_k - e_neg_k

array([0.+0.00000000e+00j, 0.+1.70710678e+00j, 0.+3.00000000e+00j,
       0.-2.92893219e-01j, 0.-3.67394040e-16j])